### ISSUE TITLE
Error on running hubot command

### ISSUE THREAD

**Issue by a19i23** [xrd/technocrat-signal#7]
When I enter `docker-compose run hubot run-hubot myfirsthubot` I get an error on the next line saying `[Tue May 24 2016 19:48:01 GMT+0000 (UTC)] ERROR v2 services token provided, please follow the upgrade instructions`

What did I do wrong?

**Comment by xrd** [comment]
Can you post the results of your versions from the installation section (https://github.com/xrd/technocrat-signal/blob/master/README.md#installation)

```
$ docker-compose --version
$ docker-machine --version
$ docker --version
```

**Comment by xrd** [comment]
Did you create an integration inside your Slack server first? This is not clearly documented in the README, but it is in the webcast.

**Comment by a19i23** [comment]
No I didn't, I will try that

**Comment by xrd** [comment]
I added pictures of the steps in the README. See if that helps.
